// Code generated by go-bindata. DO NOT EDIT.
// sources:
// kafka-topic.json
// kafka-consumergroup.json
// nginx.json
// machinegroup.json
// machineset.json

package schema


import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}


type asset struct {
	bytes []byte
	info  fileInfoEx
}

type fileInfoEx interface {
	os.FileInfo
	MD5Checksum() string
}

type bindataFileInfo struct {
	name        string
	size        int64
	mode        os.FileMode
	modTime     time.Time
	md5checksum string
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) MD5Checksum() string {
	return fi.md5checksum
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _bindataKafkatopicjson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xd4\x92\xb1\x6a\xc4\x30\x0c\x86\xf7\x3c\x85\xd0\x9c\xa5\xa5\x93\x5f\xa5\x1c\x46\x75\xd4\xf6\x38\x2b\x49\x6d\x79\x08\x25\xef\x5e\x62\xc3\xa5\x26\x29\x85\xd2\xc5\x93\xf1\xaf\x4f\xbf\x7f\x19\x7d\x76\x00\x00\x18\xdd\x3b\x0b\x59\x61\x25\x34\x50\xc4\x5c\x50\x7a\xf1\x8c\x06\x1e\xfa\x5d\x73\xa4\xfc\x36\x85\x05\x0d\xe0\x8d\x5e\x6f\x84\xdf\x8a\xba\xcc\x1b\x8f\x3a\xcd\x57\x87\x59\x5f\x4b\x19\x85\x29\xa6\xc0\xc2\xa3\x46\x34\xf0\x7c\x6f\xda\xdf\xcb\xdc\x48\xc2\x77\x6f\x5b\x8c\xfa\x1a\x71\x93\x4f\x32\xd6\x2e\xe7\x6e\x07\x57\xe7\x53\x54\x0e\x36\xdf\xfb\x73\x36\xf0\x47\xba\x06\x1e\xd0\x80\x86\xc4\x3f\x50\x25\x84\xdd\x26\x8e\xf5\x17\x55\xd8\x40\x4a\x3b\xf4\x74\x80\xd6\x63\xdf\x2f\x23\x6c\x67\x9c\xc9\xb5\x9c\xbf\xd1\xe8\xe4\x49\x78\x20\x1b\x1d\xf9\xb6\x97\xe8\x64\x92\x96\x77\x6a\x48\x22\xcb\xbf\x66\x7f\xfc\x6b\xf6\x4a\xb9\x74\xb5\x7e\xe9\xd6\xaf\x00\x00\x00\xff\xff\x30\xc9\x13\x11\x74\x05\x00\x00")

func bindataKafkatopicjsonBytes() ([]byte, error) {
	return bindataRead(
		_bindataKafkatopicjson,
		"kafka-topic.json",
	)
}



func bindataKafkatopicjson() (*asset, error) {
	bytes, err := bindataKafkatopicjsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{
		name: "kafka-topic.json",
		size: 1396,
		md5checksum: "",
		mode: os.FileMode(436),
		modTime: time.Unix(1588064915, 0),
	}

	a := &asset{bytes: bytes, info: info}

	return a, nil
}

var _bindataKafkaconsumergroupjson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xdc\x97\xdd\x6a\xeb\x30\x0c\x80\xef\xfb\x14\xc6\xd7\xbd\x39\x87\x0d\x46\x5e\x65\x14\xa3\x29\x6a\x67\xe2\xbf\x59\x76\x69\x36\xfa\xee\x23\xe9\xd6\xce\x6b\x07\x1d\x14\x32\xe7\x2a\x20\x7f\x96\xf4\x45\x89\xc1\x6f\x0b\x21\x84\x90\x8c\xcf\x64\x41\x59\x4a\x20\x1b\x71\x08\x8e\x0b\x09\x9e\x0c\xc9\x46\xfc\x5b\x9e\x62\x08\x89\x36\x3e\xf6\xb2\x11\xb2\x83\x75\x07\xf2\xcb\x62\xea\xc3\xc0\x4b\xf4\x8e\xb3\xa5\xa8\x36\xd1\xe7\x20\x47\x60\x7f\xe0\xa4\x25\xe0\x1c\xc9\x92\x4b\x2c\x1b\xf1\x78\xdc\x7d\x2a\x3c\x72\x0e\x2c\x1d\x8b\xa8\x6f\x19\x97\x25\x8b\xde\x64\xeb\xca\x74\x97\xd3\x9e\xa5\x1f\x9f\xcb\xcb\x4c\xa4\x97\xac\x23\xb5\xb2\x11\x29\x66\xfa\x81\x3a\x14\x57\x83\x3b\x97\x2f\xab\xc0\x5a\x48\x70\x82\xee\xce\xa0\xfd\xf9\xbe\x2b\x5a\xe7\x00\x58\x6b\xff\x68\x32\x27\x8a\xaa\xe2\x11\x24\x1f\x34\xd6\x2c\x00\x06\x2c\xb5\xa0\x18\xc1\xd4\x3d\x8a\x0b\x26\x35\xff\x1c\x91\xd8\xe7\x88\xa4\xba\x07\xfe\x95\xcc\x1a\x0c\x5f\x69\xf3\x7f\x3a\x9b\x59\x88\x74\xda\xb5\xb3\x10\x89\x14\x8c\x46\xe0\x09\x64\xee\x6f\xed\xc2\x81\x70\x56\x42\x56\xbb\x79\xf9\xc0\x6e\x36\x3e\x98\x39\x79\x5b\xf5\x89\x16\xbc\xd1\xd8\xd7\xda\x3d\xb9\xe1\x8e\xa2\x68\x47\x98\x93\xf6\x6e\x0a\x8f\x9b\x7e\x50\x21\x2b\xa3\xad\x4e\xb5\x0e\xa4\x30\x19\x9a\x25\xae\xdf\xc5\x92\xf5\xb1\x9f\xc9\x60\x3e\x64\x2a\x9f\xcd\x76\x28\x4c\xac\x58\xbf\x56\x7b\xf4\x7e\x3a\x84\x2d\xfe\x25\x8f\x22\xb2\x5a\x94\xf1\xd5\x62\xff\x1e\x00\x00\xff\xff\x02\x03\x3b\x96\x37\x12\x00\x00")

func bindataKafkaconsumergroupjsonBytes() ([]byte, error) {
	return bindataRead(
		_bindataKafkaconsumergroupjson,
		"kafka-consumergroup.json",
	)
}



func bindataKafkaconsumergroupjson() (*asset, error) {
	bytes, err := bindataKafkaconsumergroupjsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{
		name: "kafka-consumergroup.json",
		size: 4663,
		md5checksum: "",
		mode: os.FileMode(436),
		modTime: time.Unix(1588064915, 0),
	}

	a := &asset{bytes: bytes, info: info}

	return a, nil
}

var _bindataNginxjson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xdc\x97\x51\x6b\xac\x30\x10\x85\xdf\xfd\x15\x21\xcf\xfb\x72\x2f\xf7\x42\xf1\xaf\x94\x25\x4c\xe3\xe9\x36\x6c\x12\x6d\x26\x29\x2b\x65\xff\x7b\x51\x4b\xad\xbb\x2e\xad\x20\xac\xfa\xb4\xec\x99\x33\x93\xf9\x3c\x12\xf0\x3d\x13\x42\x08\xc9\xfa\x05\x8e\x94\x43\x24\x99\x8b\x4e\x6c\x0b\x91\x9e\x2c\x64\x2e\xfe\xec\x7a\x4d\x53\xc4\xa1\x0c\xb5\xcc\x85\xf4\x07\xe3\x4f\xf2\x5b\x31\xd6\x15\xfa\x42\xab\x9f\xbb\xb2\x74\x20\x4e\x01\x0e\x3e\xb2\xcc\xc5\xe3\x57\x53\x7f\x5e\xeb\xf3\xe4\x30\x36\xbb\x3b\xbc\xb4\xc9\xf9\x61\xff\xf8\x9c\xab\x79\xda\x26\x8e\x08\xaa\xfd\xbf\x1b\xf7\x06\xbc\x26\x13\x50\xc8\x5c\xc4\x90\x70\xc3\xd5\x2d\xa1\x1a\x56\x1e\x3e\x9c\x81\xad\xa0\x48\xbd\xe9\xdf\x95\xe9\x7c\xdd\xf7\x03\x42\xf3\xcb\x15\xe9\xa5\xec\x7f\xa9\x4c\xe5\x21\x4b\x0e\x05\x29\xd6\x64\xd7\x9d\xcc\x08\xc9\x92\x82\x9a\x8a\x13\xc0\x65\x0a\x1a\xea\xf8\xc0\x8a\x11\xde\x8c\xc6\x9a\xe3\xb9\xc9\xb3\x99\x90\xa6\xc0\x3c\x93\xe5\xe5\xd3\x6c\x02\xe4\x68\x7c\xb1\x09\x90\x80\xca\x1a\x4d\x3c\x2f\xcc\xdf\xdf\xc0\xfc\x9f\xfd\x02\xa8\xa0\x37\x05\xe4\x8c\xdf\x16\x0f\x9d\x96\xc6\x73\xa9\x4c\xe5\xab\x4a\x6b\x74\x7d\x07\x98\x59\xae\x02\xf8\xe6\x43\x40\xe1\x04\x9d\xa2\x29\xfd\x3d\x38\xe6\x7c\xc9\x74\x95\x94\x35\xce\xc4\xb5\x06\x32\x20\x69\x96\x05\xaf\x9f\xc5\xc1\x95\xa1\xde\x48\x30\x9f\x30\xcb\xca\x66\xa0\xec\xb3\xa1\xbe\xcf\xce\xd9\x47\x00\x00\x00\xff\xff\x98\x59\xf2\xf8\x11\x10\x00\x00")

func bindataNginxjsonBytes() ([]byte, error) {
	return bindataRead(
		_bindataNginxjson,
		"nginx.json",
	)
}



func bindataNginxjson() (*asset, error) {
	bytes, err := bindataNginxjsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{
		name: "nginx.json",
		size: 4113,
		md5checksum: "",
		mode: os.FileMode(436),
		modTime: time.Unix(1588064915, 0),
	}

	a := &asset{bytes: bytes, info: info}

	return a, nil
}

var _bindataMachinegroupjson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xd4\x93\xc1\x6a\xc4\x30\x0c\x44\xef\xf9\x0a\xa1\x73\x2e\x85\xd2\x83\x7f\xa5\x2c\x41\x75\xc4\xee\x82\x95\xa4\xb2\x7c\x58\x4a\xfe\xbd\x24\xa6\x4d\x5d\x67\x29\xed\x29\x3d\x85\x8c\x9e\x86\x19\x90\xdf\x1a\x00\x00\x8c\xfe\xc2\x42\x9d\xb0\x11\x3a\xc8\xe2\x3a\x30\x7a\x09\x8c\x0e\x9e\xda\x4d\xf3\x64\x7c\x1e\xf5\x86\x0e\xd0\x87\x14\x8d\xb5\xa3\x64\x63\xf4\x14\x58\xf1\x0b\x69\xb7\x69\x59\x46\x21\x7f\xb9\x0e\x7c\xd6\x31\x4d\xb8\x8e\xe7\x4c\xa1\x30\xc5\xa4\x2c\x3c\x58\x44\x07\xcf\x9f\xbb\x5b\x86\x95\x1b\x48\x6a\xa7\xb6\x64\xfc\x18\x92\x0c\xa5\xcd\xbe\x5d\x65\xfb\x51\x63\xfd\x6f\xf7\x59\xe5\xd7\x74\x55\xee\xd1\x81\x69\xe2\x3b\x54\x0e\xd1\x2d\xcd\x97\x24\x0f\x77\xb0\x9e\x8c\x36\xe8\xb1\x82\xe6\x7a\xef\x87\x0a\xcb\x37\x4e\xe4\x8f\x92\xff\xbb\xf2\x97\x3e\x07\xa9\xf2\xdb\xe8\x14\x48\xb8\xa7\x2e\x3f\x88\xff\x7c\x54\x3b\x4d\x0e\x74\x63\x85\x72\x6a\x4a\xfd\xd4\xcc\xcd\x7b\x00\x00\x00\xff\xff\x82\xc4\x36\xef\xde\x04\x00\x00")

func bindataMachinegroupjsonBytes() ([]byte, error) {
	return bindataRead(
		_bindataMachinegroupjson,
		"machinegroup.json",
	)
}



func bindataMachinegroupjson() (*asset, error) {
	bytes, err := bindataMachinegroupjsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{
		name: "machinegroup.json",
		size: 1246,
		md5checksum: "",
		mode: os.FileMode(436),
		modTime: time.Unix(1588639205, 0),
	}

	a := &asset{bytes: bytes, info: info}

	return a, nil
}

var _bindataMachinesetjson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xdc\x92\xc1\x4a\xc3\x40\x10\x86\xcf\xcd\x53\x2c\x73\xce\x45\x51\x91\xbc\x8a\x94\x65\x9c\x0e\x6d\x30\x9b\xac\x33\xb3\x60\x91\xbc\xbb\x24\x51\x63\x4c\x8b\x16\x7a\x68\x7a\x0a\x99\xfd\xe6\xe7\xff\x60\xde\x33\xe7\x9c\x03\xa5\x1d\x07\xf4\x81\x0d\xa1\x70\xc3\xb0\x7f\x30\x7c\xae\x18\x0a\xf7\x90\x8f\x33\x42\xe3\x6d\x23\x7b\x28\x1c\x50\x95\xd4\x58\x3c\x26\x6b\x94\xb0\x62\x81\x1f\xa4\xed\x63\xb7\x0c\x01\x69\x57\xd6\xac\x6c\xd0\x3f\xb6\x03\x03\x81\x51\x93\x70\xe0\xda\x14\x0a\xf7\xf4\xbd\x39\x36\xe8\xb9\x1a\xc3\xef\x9c\x7c\x4a\x50\x53\xa5\x50\x4f\x43\x0e\x87\xcd\x42\xbf\x14\xfa\xff\xfc\x30\x2b\xfc\x9a\x4a\xe1\x0d\x14\xce\x24\xf1\x11\x6a\x28\xe1\x3b\xeb\xae\xc9\xcd\x11\x6c\x83\x86\x23\x74\x37\x83\xda\xf9\xde\x1f\x0a\xdd\x57\x23\xd2\x92\xfb\x2f\xb4\xfa\xe7\x49\x6e\xa5\x49\xf1\xa2\x4e\x68\xb5\x3a\xb5\xf9\x92\x2f\x48\x58\x9b\x24\xc4\xfe\xe5\x51\xbd\x46\x26\x2f\x1c\xab\x92\x50\xcf\x2a\x74\xfb\x1f\xa1\xfb\x73\xfb\x5c\x91\x4a\x28\xeb\xab\xd2\xc1\xb7\xcb\xd2\x99\x4c\xd6\xd9\x74\xbe\xce\xda\xec\x23\x00\x00\xff\xff\x19\xf7\xdc\x33\xf1\x07\x00\x00")

func bindataMachinesetjsonBytes() ([]byte, error) {
	return bindataRead(
		_bindataMachinesetjson,
		"machineset.json",
	)
}



func bindataMachinesetjson() (*asset, error) {
	bytes, err := bindataMachinesetjsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{
		name: "machineset.json",
		size: 2033,
		md5checksum: "",
		mode: os.FileMode(436),
		modTime: time.Unix(1588639184, 0),
	}

	a := &asset{bytes: bytes, info: info}

	return a, nil
}


//
// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
//
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, &os.PathError{Op: "open", Path: name, Err: os.ErrNotExist}
}

//
// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
// nolint: deadcode
//
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

//
// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or could not be loaded.
//
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, &os.PathError{Op: "open", Path: name, Err: os.ErrNotExist}
}

//
// AssetNames returns the names of the assets.
// nolint: deadcode
//
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

//
// _bindata is a table, holding each asset generator, mapped to its name.
//
var _bindata = map[string]func() (*asset, error){
	"kafka-topic.json":         bindataKafkatopicjson,
	"kafka-consumergroup.json": bindataKafkaconsumergroupjson,
	"nginx.json":               bindataNginxjson,
	"machinegroup.json":        bindataMachinegroupjson,
	"machineset.json":          bindataMachinesetjson,
}

//
// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
//
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, &os.PathError{
					Op: "open",
					Path: name,
					Err: os.ErrNotExist,
				}
			}
		}
	}
	if node.Func != nil {
		return nil, &os.PathError{
			Op: "open",
			Path: name,
			Err: os.ErrNotExist,
		}
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}


type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{Func: nil, Children: map[string]*bintree{
	"kafka-consumergroup.json": {Func: bindataKafkaconsumergroupjson, Children: map[string]*bintree{}},
	"kafka-topic.json": {Func: bindataKafkatopicjson, Children: map[string]*bintree{}},
	"machinegroup.json": {Func: bindataMachinegroupjson, Children: map[string]*bintree{}},
	"machineset.json": {Func: bindataMachinesetjson, Children: map[string]*bintree{}},
	"nginx.json": {Func: bindataNginxjson, Children: map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
