topicEventResendTime = 30 #seconds

[rabbitmq]
url = "amqp://admin:adminpass@rabbitmq.alameda.svc.cluster.local:5672"
connRetry = 10
connRetryInterval = 3 #seconds

[datahub]
address = "datahub.alameda.svc.cluster.local:50050"
connRetry = 5

[log]
setLogcallers = true
outputLevel = "info" # debug, info, warn, error, fatal, none

[k8sWebhook]
port = 50443