{
 "title": "Cost Allocation",
 "time": { "from": "now/M", "to": "now/M" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "Namespace",
    "query": "show tag values on alameda_cluster_status from namespace with key = \"name\""
   },
   {
    "name": "current_provider",
    "query": "select io_provider from alameda_cluster_status..node order by time desc limit 1"
   },
   {
    "name": "current_cost_starttime",
    "query": "select starttime from alameda_fedemeter..calculate_instance where time >= now() -2h and  granularity = '3600' order by time desc limit 1 "
   },
   {
    "name": "current_cost",
    "query": "select sum(totalcost) as totalcost from alameda_fedemeter..calculate_instance where starttime = $current_cost_starttime fill(0)"
   },
   {
    "name": "current_region",
    "query": "select io_region from alameda_cluster_status..node order by time desc limit 1"
   },
   {
    "name": "ns_starttime",
    "query": "select last(starttime) from alameda_fedemeter..cost_namespace where granularity = '3600' and type = '0' "
   },
   {
    "name": "app_starttime",
    "query": "select last(starttime) from alameda_fedemeter..cost_app where granularity = '3600' and type = '0' and namespacename = '$ns'"
   },
   {
    "name": "ns_top_5",
    "query": "select namespacename from (select top(costpercentage, namespacename, 5) from alameda_fedemeter..cost_namespace where granularity = '3600' and type = '0' and starttime = '$ns_starttime' )"
   },
   {
    "name": "app_top_5",
    "query": "select appname from (select top(costpercentage, appname, 5) from alameda_fedemeter..cost_app where granularity = '3600' and type = '0' and starttime = '$app_starttime' and namespacename = '$ns')"
   },
   {
    "name": "ns_starttime_monthly",
    "query": "select last(starttime) from alameda_fedemeter..cost_namespace where granularity = '86400' and type = '0'"
   },
   {
    "name": "app_starttime_monthly",
    "query": "select last(starttime) from alameda_fedemeter..cost_app where granularity = '86400' and type = '0' and namespacename = '$ns'"
   },
   {
    "name": "ns_top_5_monthly",
    "query": "select namespacename from (select top(costpercentage, namespacename, 5) from alameda_fedemeter..cost_namespace where granularity = '86400' and type = '0' and starttime = '$ns_starttime_monthly' )"
   },
   {
    "name": "app_top_5_monthly",
    "query": "select appname from (select top(costpercentage, appname, 5) from alameda_fedemeter..cost_app where granularity = '86400' and type = '0' and starttime = '$app_starttime_monthly' and namespacename = '$ns')"
   },
   {
    "name": "count_of_hourlycost",
    "query": "select count(sum) -1 from (select sum(numMeasurements) from _internal..\"database\" where $timeFilter  and time <= now() group by time(3600s) fill(0));"
   }
  ]
 },
 "panels": [
  { "title": "Monthly Cluster Total Cost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Provider",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <img id=\"config_provider\" style=\"display:block; margin-left:auto; margin-right:auto;\">\n    </td>\n  </tr>\n</table>\n<script>\n  var currentProvider = `${current_provider}`.toLowerCase();\n  if (currentProvider === 'aws') {\n    document.getElementById('config_provider').src = 'https://d1.awsstatic.com/gamedev/gamelift/awshomepage.8845ec5b83a849d57f677cf9010c25abd357ea2e.PNG';\n    document.getElementById('config_provider').style.height = '41%';\n  } else if ( currentProvider === 'azure') {\n    document.getElementById('config_provider').src = 'https://www.net4all.ch/wp-content/uploads/sites/4/2018/04/azure-logo_200x200.png';\n    document.getElementById('config_provider').style.height = '50%';\n    document.getElementById('config_provider').style.width = '50%';\n  } else if ( currentProvider === 'gcp') {\n    document.getElementById('config_provider').src = 'https://miro.medium.com/max/1200/1*eSQnSxgOwNWtjsnbBl3w4A.png';\n    document.getElementById('config_provider').style.height = '40%';\n  }\n  //document.getElementById('config_provider').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'black'\n</script>\n"
  },
  {
   "title": "Current Cost",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"config_cost\" type=\"text/JavaScript\" style=\"text-align:center;font-size:30px; color:black\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var cost = `$${$current_cost.toFixed(2)}<div style=\"font-size:18px; color:black\">per month</div>`;\n  document.getElementById('config_cost').innerHTML = cost;\n  document.getElementById('config_cost').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'cadetblue';\n</script>\n<style>\n .markdown-html table {\n  border: none !important\n}\n .markdown-html tr {\n  border: none !important\n}\n .markdown-html td {\n  border: none !important\n}\n </style>"
  },
  {
   "title": "Region",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"config_region\" type=\"text/JavaScript\" style=\"text-align:center;font-size:20px\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var region = `${current_region}`;\n  document.getElementById('config_region').innerHTML = region;\n</script>"
  },
  {
   "title": "Current Cluster Configuration",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select  \"name\", io_role, io_instance_type, node_cpu_cores, node_memory_bytes, io_storage_size from alameda_cluster_status..node\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 5 },
   "content": "<script>\n  $('#panel-12 .table-panel-table tbody').on('DOMSubtreeModified', function() {\n    var dataLength = this.children.length;\n    if (dataLength > 0) {\n      for(var i = 0; i < dataLength; i++) {\n        if (this.children[i].innerText.indexOf('idle') !== -1) {\n          this.children[i].style.backgroundColor = '#3f6833';\n        }\n      }\n    }\n  });\n  \n  $('#panel-48 .table-panel-table tbody').on('DOMSubtreeModified', function() {\n    var dataLength = this.children.length;\n    if (dataLength > 0) {\n      for(var i = 0; i < dataLength; i++) {\n        if (this.children[i].innerText.indexOf('idle') !== -1) {\n          this.children[i].style.backgroundColor = '#3f6833';\n        }\n      }\n    }\n  });\n</script>\n<style>\n  #panel-36 {\n   display:none\n  }\n\n  .pieLabel > div {\n   color: white !important;\n  }\n </style>"
  },
  { "title": "Current Resource Cost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Namespace Cost Percentage(Last Hour)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum from (select 100 - sum(costpercentage) from alameda_fedemeter..cost_namespace where granularity = '3600' and type = '0' and namespacename =~ /^[[ns_top_5]]$/ and starttime = '$ns_starttime' group by time(3600s)) where sum >= 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_namespacename",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(costpercentage) from alameda_fedemeter..cost_namespace where granularity = '3600' and type = '0' and namespacename =~ /^[[ns_top_5]]$/ and starttime = '$ns_starttime' group by namespacename, time(3600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Application Cost Percentage - $ns(Last Hour)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_appname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(costpercentage) from alameda_fedemeter..cost_app where granularity = '3600' and type = '0' and appname =~ /^[[app_top_5]]$/ and starttime = '$app_starttime' and namespacename = '$ns' group by appname, time(3600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Namespace(Last Hour)",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(\"\") as namespacename, 100 - sum(costpercentage) as costpercentage, (($current_cost + 0) / 730) - sum(workloadcost) as workloadcost from alameda_fedemeter..cost_namespace where granularity = '3600' and type = '0' and namespacename =~ /^[[ns_top_5]]$/ and starttime = '$ns_starttime' ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select namespacename, costpercentage, workloadcost from alameda_fedemeter..cost_namespace where granularity = '3600' and type = '0' and namespacename =~ /^[[ns_top_5]]$/ and starttime = '$ns_starttime' ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cost Per Hour: Observation, and Prediction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "$tag_namespacename(observation)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(workloadcost) from alameda_fedemeter..cost_namespace where granularity = '3600' and type = '0' and time >= now()-5d and time <= now() group by time(3600s), namespacename ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_namespacename(prediction)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(workloadcost) from alameda_fedemeter..cost_namespace where granularity = '3600' and type = '1' and time >= now()-1h  and time <= now() +1d group by time(3600s), namespacename",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Monthly Resource Cumulative Cost",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Namespace Cost Percentage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 23 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum from (select ((($current_cost + 0) * ($count_of_hourlycost + 0)) / 730) - sum(workloadcost) from alameda_fedemeter..cost_namespace where granularity = '3600' and type = '0' and namespacename =~ /^[[ns_top_5_monthly]]$/ and $timeFilter) where sum >= 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_namespacename",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(workloadcost) from alameda_fedemeter..cost_namespace where granularity = '3600' and type = '0' and namespacename =~ /^[[ns_top_5_monthly]]$/ and $timeFilter group by namespacename",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Application Cost Percentage - $ns",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 23 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_appname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(workloadcost) from alameda_fedemeter..cost_app where granularity = '3600' and type = '0' and appname =~ /^[[app_top_5_monthly]]$/ and $timeFilter and namespacename = '$ns' group by appname",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Namespace",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(\"\") as namespacename, 100 - (sum(workloadcost) * 730 * 100 / ($count_of_hourlycost + 0) / ($current_cost + 0)) as costpercentage, ((100 - (sum(workloadcost) * 730 * 100 / ($count_of_hourlycost + 0) / ($current_cost + 0))) / 100) * ($count_of_hourlycost + 0) / 730 * ($current_cost + 0 )  as workloadcost from alameda_fedemeter..cost_namespace where granularity = '3600' and type = '0' and namespacename =~ /^[[ns_top_5_monthly]]$/ and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(workloadcost) * 730 * 100 / ($count_of_hourlycost + 0) / ($current_cost + 0) as costpercentage, sum(workloadcost) as  workloadcost from alameda_fedemeter..cost_namespace where granularity = '3600' and type = '0' and namespacename =~ /^[[ns_top_5_monthly]]$/ and $timeFilter group by namespacename",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cumulative Cost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "$tag_namespacename",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select cumulative_sum(workloadcost) from alameda_fedemeter..cost_namespace where granularity = '3600' and type = '0' and $timeFilter group by namespacename",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_namespacename(prediction)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select history + prediction from (select sum(workloadcost) as history from alameda_fedemeter..cost_namespace where granularity = '3600' and type = '0' and $timeFilter group by namespacename),\n(select cumulative_sum(workloadcost) as prediction from alameda_fedemeter..cost_namespace where granularity = '86400' and type = '1' and $timeFilter and time >= now() group by namespacename) group by namespacename fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select cumulative_sum(sum(workloadcost)) from alameda_fedemeter..cost_namespace where granularity = '3600' and type = '0' and $timeFilter group by time(3600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total(prediction)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select history + prediction from (select sum(workloadcost) as history from alameda_fedemeter..cost_namespace where granularity = '3600' and type = '0' and $timeFilter), (select cumulative_sum(sum(workloadcost)) as prediction from alameda_fedemeter..cost_namespace where granularity = '86400' and type = '1' and $timeFilter and time >= now() group by time(86400s)) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}